when:
  - event: [push, tag, deployment]

steps:
  - name: test
    image: node
    commands:
      - npm ci
      - npx nx format:check
      - npx nx affected -t lint --parallel=3
      - npx nx affected -t test --parallel=3 --configuration=ci
      - npx nx affected -t build --parallel=3
