name: Publish

on:
  push:
    tags:
      - '^\d+\.\d+\.\d+(-\w+\.\d+)?'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npx nx run-many -t publish --configuration=production --ver=${{github.ref_name}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
